console.log('🔥 Firebase Anonymous Authentication Setup Guide');
console.log('==================================================');
console.log('');
console.log('To enable anonymous authentication for quiz uploads:');
console.log('');
console.log('1. 📱 Open Firebase Console:');
console.log('   https://console.firebase.google.com/');
console.log('');
console.log('2. 🏗️ Select your project:');
console.log('   hacklite-9c06e');
console.log('');
console.log('3. 🔐 Go to Authentication:');
console.log('   Click "Authentication" in the left sidebar');
console.log('');
console.log('4. ⚙️ Go to Sign-in method:');
console.log('   Click the "Sign-in method" tab');
console.log('');
console.log('5. ➕ Enable Anonymous:');
console.log('   Find "Anonymous" in the provider list');
console.log('   Click the edit icon (pencil)');
console.log('   Toggle "Enable" to ON');
console.log('   Click "Save"');
console.log('');
console.log('6. 🚀 Run the upload script:');
console.log('   npm run upload-web');
console.log('');
console.log('⚠️  Security Note:');
console.log('Anonymous authentication allows anyone to sign in without credentials.');
console.log('For production apps, consider using proper user authentication instead.');
console.log('');
console.log('Alternative: Use Service Account method (more secure):');
console.log('npm run upload');
