name: WaveWords CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.35.3'
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  # Step 1: Code Quality & Testing
  test:
    name: Test & Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Verify the installation
        run: flutter doctor -v

      - name: Analyze project source
        run: |
          echo "Running Flutter analysis..."
          flutter analyze --no-fatal-infos || echo "Analysis completed with warnings (non-blocking)"

      - name: Check formatting
        run: |
          echo "Checking code formatting..."
          dart format --output=none --set-exit-if-changed . || echo "Formatting issues found (non-blocking)"

      - name: Run widget tests
        run: flutter test

      - name: Generate test coverage
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
          fail_ci_if_error: false

  # Step 2: Build APK & AAB
  build:
    name: Build APK & AAB
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug --build-number=${{ env.BUILD_NUMBER }}

      - name: Build release APK
        run: flutter build apk --release --build-number=${{ env.BUILD_NUMBER }}

      - name: Build release app bundle (AAB)
        run: flutter build appbundle --release --build-number=${{ env.BUILD_NUMBER }}

      - name: List build outputs
        run: |
          echo "APK Files:"
          find build/app/outputs/flutter-apk/ -name "*.apk" -exec ls -la {} \;
          echo ""
          echo "AAB Files:"
          find build/app/outputs/bundle/ -name "*.aab" -exec ls -la {} \;

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: wavewords-debug-apk-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: wavewords-release-apk-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 90

      - name: Upload release AAB
        uses: actions/upload-artifact@v4
        with:
          name: wavewords-release-aab-${{ github.run_number }}
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 90
